### PR TITLE
UI and content amends

### PR DESCRIPTION
**Pull request by vlbee**
Hi @zimbatm 👋

- made nav bar sticky on the top
- made font/paragraph style consistent on index.html
- amended padding of containers on index.html
- updated wording for Call for proposals, registration, program, hackathon. 
- made required info into a list on sponsoring.html
- fixed css layout of footer

I added deadline information for the Proposals and Hackathon form submissions - please check you are happy with the dates. 

There are a lot of diffs on the css because of autoformatting  (2 spaces vs 2 tabs - sorry!)

If you need any more tweaks or if you notice anything broken let me know or tell @teh.

### CODE REVIEW

**Comment by zimbatm** [comment]
Hi @vlbee, thanks a lot for all the work you put in this PR!

The sticky header is a great idea and I like the added whitespaces.

I did a few changes myself this weekend, including releasing the tickets. Would it be difficult for you to rebase your changes on top of master?

On my machines the twitter link wraps the page, things are a bit large in general. I think it depends on the screen size:

image

**Comment by vlbee** [comment]
No problem! Will have a look tonight or tomorrow.

**Comment by vlbee** [comment]
@zimbatm 
I merged the changes, fixed the nav bar and made the title a bit smaller so it would fit better on mobile.  Hopefully it looks better now.  :) 

Just Fyi - the Google Form for proposals says the deadline is June still. You will want to change this to July  to match the updated info on the website.

**Comment by zimbatm** [comment]
Brilliant, thanks! Should be up in 5-10 minutes.

**Pull request merged**
